FROM tomcat:9.0

ENV HOSTURL=www.clickdimensions.com
ENV CONTEXTPATH=/links/TestPDFfile.pdf
ENV MAXKEYWORDS=3


ADD  ./target/pass-keyword-service.war /usr/local/tomcat/webapps

CMD ["catalina.sh", "run"]